import Table from "react-bootstrap/Table";

export default function CuentaBancariaTable() {
  return (
    <>
      <div style={{ maxHeight: "550px", overflowY: "auto" }}>
        <Table striped bordered hover>
          <thead>
            <tr>
              <th style={{ backgroundColor: "#2b3036", color: "white" }}>#</th>
              <th style={{ backgroundColor: "#2b3036", color: "white" }}>No. Cuenta</th>
              <th style={{ backgroundColor: "#2b3036", color: "white" }}>Tipo Cuenta</th>
              <th style={{ backgroundColor: "#2b3036", color: "white" }}>Nombre</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>00000001</td>
              <td>Monetaria</td>
              <td>Mark</td>
            </tr>
            <tr>
              <td>2</td>
              <td>00000002</td>
              <td>Ahorro</td>
              <td>Jane</td>
            </tr>
            <tr>
              <td>3</td>
              <td>00000003</td>
              <td>Monetaria</td>
              <td>John</td>
            </tr>
            <tr>
              <td>4</td>
              <td>00000004</td>
              <td>Ahorro</td>
              <td>Alice</td>
            </tr>
            <tr>
              <td>5</td>
              <td>00000005</td>
              <td>Monetaria</td>
              <td>Bob</td>
            </tr>
            <tr>
              <td>6</td>
              <td>00000006</td>
              <td>Ahorro</td>
              <td>Eve</td>
            </tr>
            <tr>
              <td>7</td>
              <td>00000007</td>
              <td>Monetaria</td>
              <td>Michael</td>
            </tr>
            <tr>
              <td>8</td>
              <td>00000008</td>
              <td>Ahorro</td>
              <td>Emily</td>
            </tr>
            <tr>
              <td>9</td>
              <td>00000009</td>
              <td>Monetaria</td>
              <td>David</td>
            </tr>
            <tr>
              <td>10</td>
              <td>00000010</td>
              <td>Ahorro</td>
              <td>Sarah</td>
            </tr>
            <tr>
              <td>11</td>
              <td>00000011</td>
              <td>Monetaria</td>
              <td>Thomas</td>
            </tr>
            <tr>
              <td>12</td>
              <td>00000012</td>
              <td>Ahorro</td>
              <td>Olivia</td>
            </tr>
            <tr>
              <td>13</td>
              <td>00000013</td>
              <td>Monetaria</td>
              <td>Liam</td>
            </tr>
            <tr>
              <td>14</td>
              <td>00000014</td>
              <td>Ahorro</td>
              <td>Sophia</td>
            </tr>
            <tr>
              <td>15</td>
              <td>00000015</td>
              <td>Monetaria</td>
              <td>Ethan</td>
            </tr>
            <tr>
              <td>16</td>
              <td>00000016</td>
              <td>Ahorro</td>
              <td>Isabella</td>
            </tr>
            <tr>
              <td>17</td>
              <td>00000017</td>
              <td>Monetaria</td>
              <td>James</td>
            </tr>
            <tr>
              <td>18</td>
              <td>00000018</td>
              <td>Ahorro</td>
              <td>Charlotte</td>
            </tr>
            <tr>
              <td>19</td>
              <td>00000019</td>
              <td>Monetaria</td>
              <td>William</td>
            </tr>
            <tr>
              <td>20</td>
              <td>00000020</td>
              <td>Ahorro</td>
              <td>Amelia</td>
            </tr>
          </tbody>
        </Table>
      </div>
    </>
  );
}
